
PATH:
  DATASET_DIR: 'dataset/'
  PKL_PATH: 'dataset/database.pkl'

INFO:
  PICTURE_PROMPT: 'This is a Facial Recognition System made for Healthcare Personnel. Please use the Facial Verification App to log in to the SurgiSense Platform.'
  WEBCAM_PROMPT: 'This is a Facial Recognition System made for Healthcare Personnel. Please use the Facial Verification App to log in to the SurgiSense Platform.'
